services:
  - type: web
    name: anti-vape-campaign
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd anti-vape-campaign && gunicorn -c ../gunicorn_config.py run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0